/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarAmigo.java
 *
 * Created on Dec 3, 2011, 10:55:42 AM
 */
package Clases;

import java.awt.Image;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class BuscarAmigo extends javax.swing.JFrame {

    /** Creates new form BuscarAmigo */
       String mail;
    String mail1;
    public BuscarAmigo(String correo,String correo1) {
        mail=correo;
        mail1=correo1;
        Perfil p=new Perfil(correo);
        initComponents();
        this.txt_nombre.setText(p.getNombre());
        this.txt_genero.setText(p.getGenero());
        Calendar c=Calendar.getInstance();
        c.setTime(new Date(p.getFechaInicio()));
        this.txt_fechaInicio.setText(p.fecha(c));
        this.lbl_imagen.setSize(115,104);
        ImageIcon foto=new ImageIcon(p.getFoto());
        ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.lbl_imagen.getWidth(), this.lbl_imagen.getHeight(), Image.SCALE_DEFAULT));
        this.lbl_imagen.setIcon(fotoReal1);
        try {
            p.close();
        } catch (IOException ex) {
            System.out.println("yas");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_fechaInicio = new javax.swing.JTextField();
        txt_genero = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        lbl_imagen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        bot_enviarS = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(460, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 179, 51, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Genero: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 217, 48, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Miembro desde:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 255, 87, 15);

        txt_fechaInicio.setEditable(false);
        getContentPane().add(txt_fechaInicio);
        txt_fechaInicio.setBounds(125, 253, 170, 20);

        txt_genero.setEditable(false);
        getContentPane().add(txt_genero);
        txt_genero.setBounds(125, 215, 88, 20);

        txt_nombre.setEditable(false);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(125, 177, 170, 20);

        lbl_imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_imagen);
        lbl_imagen.setBounds(168, 19, 115, 104);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases/Imagenes/logo1.jpg"))); // NOI18N

        jToggleButton2.setText("Cerrar");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });

        bot_enviarS.setText("Enviar Solicitud");
        bot_enviarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_enviarSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(bot_enviarS, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(bot_enviarS))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        dispose();
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void bot_enviarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_enviarSMouseClicked
        ManageFriends mf=new ManageFriends(mail1);
        if(mf.enviarSolictud(mail)){
            JOptionPane.showMessageDialog(null,"Solicitud Enviada Exitosamente.");
        }else{
            JOptionPane.showMessageDialog(null,"Este Usuario Ya esta en Tu Lista de Amistades o Ya se le Fue Enviada una Solicitud.");
        }
        try {
            mf.cerrarConexion();
        } catch (IOException ex) {
            System.out.println("asdjasdjieie");
        }
    }//GEN-LAST:event_bot_enviarSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BuscarAmigo("gto","german.reyes10@gmail.com").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bot_enviarS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JTextField txt_fechaInicio;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
