/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearCuenta.java
 *
 * Created on Nov 22, 2011, 9:41:40 AM
 */
package Clases;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class CrearCuenta extends javax.swing.JFrame {

    /** Creates new form CrearCuenta */
    RegistrarUsuario reg=new RegistrarUsuario();
    public CrearCuenta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        cmb_genero = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btm_crear = new javax.swing.JButton();
        cmb_dia = new javax.swing.JComboBox();
        cmb_mes = new javax.swing.JComboBox();
        cmb_año = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 106, 101, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel3.setText("Genero:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 151, 62, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 270, 48, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel5.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 208, 167, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 354, 75, 22);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(214, 106, 270, 20);
        getContentPane().add(txt_tel);
        txt_tel.setBounds(224, 354, 326, 20);

        cmb_genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(cmb_genero);
        cmb_genero.setBounds(214, 158, 157, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel10.setText("Contraseña:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 306, 94, 22);
        getContentPane().add(txt_email);
        txt_email.setBounds(224, 273, 270, 20);
        getContentPane().add(txt_pass);
        txt_pass.setBounds(224, 313, 151, 20);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases/Imagenes/crearcuenta.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 270, 55);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel7.setText("DD/MM/AA");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 210, 80, 14);

        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 400, 100, 23);

        btm_crear.setText("Crear Cuenta");
        btm_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btm_crearMouseClicked(evt);
            }
        });
        jPanel1.add(btm_crear);
        btm_crear.setBounds(120, 400, 150, 23);

        cmb_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(cmb_dia);
        cmb_dia.setBounds(210, 210, 60, 20);

        cmb_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cmb_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mesActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_mes);
        cmb_mes.setBounds(290, 210, 60, 20);

        cmb_año.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", " " }));
        cmb_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_añoActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_año);
        cmb_año.setBounds(370, 210, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm_crearMouseClicked
        
        LogIn log=new LogIn();
        
        String nombre=this.txt_nombre.getText();
        char gen= (this.cmb_genero.getSelectedIndex()==0 ? 'M' : 'F');
        String m=(String) this.cmb_mes.getSelectedItem();
        String d=(String) this.cmb_dia.getSelectedItem();
        String a=(String) this.cmb_año.getSelectedItem();
        int mes=Integer.parseInt(m);
        int dia=Integer.parseInt(d);
        int anio=Integer.parseInt(a)-1900;
        Date Nacimiento=new Date(anio,mes-1,dia);
        long fechaN=Nacimiento.getTime();
        String email=this.txt_email.getText();
        String pass=this.txt_pass.getText();
        int tel=Integer.parseInt(this.txt_tel.getText());
        Date fechaAhora=new Date();
        if(reg.agregarUsuario(nombre, gen, fechaN, tel, fechaAhora.getTime(), email,pass)){
           JOptionPane.showMessageDialog(this,"Cuenta Creada Exitosamente!.");
           log.setVisible(true);
           dispose();
        }else{
            JOptionPane.showMessageDialog(this,"El correo Ingresado Ya existe.");
        }
    }//GEN-LAST:event_btm_crearMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        LogIn l=new LogIn();
        dispose();
        l.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void cmb_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_mesActionPerformed

    private void cmb_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_añoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_crear;
    private javax.swing.JComboBox cmb_año;
    private javax.swing.JComboBox cmb_dia;
    private javax.swing.JComboBox cmb_genero;
    private javax.swing.JComboBox cmb_mes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
