/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Profile.java
 *
 * Created on Nov 22, 2011, 3:29:53 PM
 */
package Clases;

import java.awt.Image;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class Profile extends javax.swing.JFrame {

    /** Creates new form Profile */
    String email;
    ImageIcon fotoP;
    
    public Profile(String correo) {
        this.email=correo;
       ManageFriends mf=new ManageFriends(correo);
        int cont=0;
        initComponents();
       Perfil p=new Perfil(correo);
       Posts po=new Posts(correo);
        Calendar c=Calendar.getInstance();
        c.setTime(new Date(p.getFechaNacimiento()));
        this.jFotoPerfil.setSize(199,172);
        addComboBox(mf.getCorreoAmigos());
        this.jTextPane1.setText("Fecha de Nacimiento: \n"+p.fecha(c) +"\n\n"+
                                "Telefono: "+p.getTel()+"\n\n"+
                                "Correo: "+p.getEmail()+"\n\n"+
                                "Genero: "+p.getGenero());
        this.jLabelNombre.setText(p.getNombre());
        this.txt_posts.setText(po.getPosts());
        if(p.getFoto().equals("")){ 
            this.jFotoPerfil.setIcon(setFoto("src\\Clases\\Imagenes\\perfil.jpg"));
        }else{
            this.jFotoPerfil.setIcon(setFoto(p.getFoto()));
        }
        this.txt_amigos.setText(mf.listarAmigos());
        this.lbl_amigos.setText("Amigos: "+mf.cantAmigos());
        try {
            p.close();
            po.cerrar();
            mf.cerrarConexion();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bot_fotoperfil = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jFotoPerfil = new javax.swing.JLabel();
        txt_aPost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bot_agregarPost = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_posts = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_amigos = new javax.swing.JTextArea();
        lbl_amigos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bot_buscarA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        bot_cerrarS = new javax.swing.JToggleButton();
        cmb_amigos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        bot_verPerfil = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1061, 750));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        bot_fotoperfil.setText("Cambiar Foto");
        bot_fotoperfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_fotoperfilMouseClicked(evt);
            }
        });
        bot_fotoperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_fotoperfilActionPerformed(evt);
            }
        });
        jPanel1.add(bot_fotoperfil);
        bot_fotoperfil.setBounds(50, 250, 150, 23);

        jLabelNombre.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNombre.setFont(new java.awt.Font("Ravie", 2, 20)); // NOI18N
        jPanel1.add(jLabelNombre);
        jLabelNombre.setBounds(23, 11, 327, 32);

        jFotoPerfil.setText("  ");
        jFotoPerfil.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jFotoPerfil);
        jFotoPerfil.setBounds(20, 50, 199, 172);
        jPanel1.add(txt_aPost);
        txt_aPost.setBounds(10, 308, 351, 46);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel2.setText("Nuevo Post");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(23, 280, 90, 17);

        bot_agregarPost.setText("Agregar Post");
        bot_agregarPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_agregarPostMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bot_agregarPostMouseEntered(evt);
            }
        });
        jPanel1.add(bot_agregarPost);
        bot_agregarPost.setBounds(210, 370, 150, 23);

        txt_posts.setColumns(20);
        txt_posts.setEditable(false);
        txt_posts.setRows(5);
        jScrollPane3.setViewportView(txt_posts);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 422, 616, 274);

        txt_amigos.setColumns(20);
        txt_amigos.setEditable(false);
        txt_amigos.setFont(new java.awt.Font("Monospaced", 0, 14));
        txt_amigos.setRows(5);
        jScrollPane2.setViewportView(txt_amigos);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(397, 39, 309, 258);

        lbl_amigos.setFont(new java.awt.Font("Tahoma", 3, 14));
        lbl_amigos.setForeground(new java.awt.Color(204, 255, 255));
        lbl_amigos.setText("Amigos");
        jPanel1.add(lbl_amigos);
        lbl_amigos.setBounds(410, 10, 107, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Informacion Personal");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(819, 11, 167, 17);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(819, 39, 222, 201);

        jButton1.setText("Modificar Perfil");
        jButton1.setActionCommand("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(819, 258, 180, 23);

        jButton2.setText("Ver Solicitudes de Amistad");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(819, 299, 210, 23);

        bot_buscarA.setText("Buscar Amigo");
        bot_buscarA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_buscarAMouseClicked(evt);
            }
        });
        jPanel1.add(bot_buscarA);
        bot_buscarA.setBounds(819, 343, 180, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel4.setText("Posts Mas Recientes.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 399, 143, 17);

        jButton4.setText("Regresar Al Inicio");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(819, 384, 180, 23);

        bot_cerrarS.setText("Cerrar Sesion");
        bot_cerrarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_cerrarSMouseClicked(evt);
            }
        });
        jPanel1.add(bot_cerrarS);
        bot_cerrarS.setBounds(819, 425, 180, 23);

        cmb_amigos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel1.add(cmb_amigos);
        cmb_amigos.setBounds(494, 327, 212, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Visitar Perfil Amigo: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(366, 328, 160, 15);

        bot_verPerfil.setText("Ir a Perfil");
        bot_verPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_verPerfilMouseClicked(evt);
            }
        });
        jPanel1.add(bot_verPerfil);
        bot_verPerfil.setBounds(586, 365, 120, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases/Imagenes/blanco-sobre-azul-wallpapers_27710_1920x1200.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1130, 740);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases/Imagenes/logo2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(990, 620, 198, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1077)/2, (screenSize.height-756)/2, 1077, 756);
    }// </editor-fold>//GEN-END:initComponents

    private void bot_fotoperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_fotoperfilActionPerformed
        
    }//GEN-LAST:event_bot_fotoperfilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bot_fotoperfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_fotoperfilMouseClicked
       ImageIcon foto= this.getFoto();

        if ( foto!= null){
            this.jFotoPerfil.setIcon(foto);

        }
    }//GEN-LAST:event_bot_fotoperfilMouseClicked

    private void bot_cerrarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_cerrarSMouseClicked
        LogIn l=new LogIn();
        dispose();
        l.setVisible(true);
        
    }//GEN-LAST:event_bot_cerrarSMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ModifPerfil m=new ModifPerfil(email);
        dispose();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bot_agregarPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_agregarPostMouseClicked

       Perfil p=new Perfil(email);
        Posts po=new Posts(email);
        ManageFriends mf=new ManageFriends(email);
        Calendar c=Calendar.getInstance();
        String e=this.txt_aPost.getText()+"\t\t Posteado a las: "+c.get(Calendar.HOUR)+":"+(c.get(Calendar.MINUTE) <10 ? "0" : "")+c.get(Calendar.MINUTE)+" "+(c.get(Calendar.AM_PM)==1 ? "PM" : "AM")+
                " del "+c.get(Calendar.DATE)+"/"+c.get(Calendar.MONTH)+"/"+c.get(Calendar.YEAR) +"\n\n";
        po.agregarPost(e);
        mf.agregarPostInicio(p.getNombre(), e);
        po.agegarPostInicio(email,p.getNombre(), e);
        this.txt_posts.setText(po.getPosts());
        //this.txt_posts.append(this.txt_aPost.getText()+"\t\t Posteado a las: "+c.get(Calendar.HOUR)+":"+c.get(Calendar.MINUTE)+"\n\n"+po.getPosts());

        JOptionPane.showMessageDialog(null, "Post Agregado.");
        this.txt_aPost.setText("");
        try {
            p.close();
            po.cerrar();
            mf.cerrarConexion();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bot_agregarPostMouseClicked

    private void bot_agregarPostMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_agregarPostMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bot_agregarPostMouseEntered

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        HomeFeed home=new HomeFeed(email);
        dispose();
        home.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void bot_buscarAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_buscarAMouseClicked
        Perfil p=new Perfil(email);
        String email1=JOptionPane.showInputDialog("Ingrese la Direccion del Amigo a Buscar.");
        if(p.buscarAmigo(email1)){
            BuscarAmigo b=new BuscarAmigo(email1,email);
            b.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Usuario no Encontrado.");
        }
        try{
        p.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bot_buscarAMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        SolicitudesPendientes sp=new SolicitudesPendientes(email);
        dispose();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void bot_verPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_verPerfilMouseClicked
       if(!this.cmb_amigos.getSelectedItem().equals(" ")){
           ProfileAmigo pf=new ProfileAmigo((String)this.cmb_amigos.getSelectedItem());
           pf.setVisible(true);
       }
    }//GEN-LAST:event_bot_verPerfilMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Profile("prueba3").setVisible(true);
            }
        });
    }
        private ImageIcon getFoto() {
        Perfil p=new Perfil(email);
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Foto de Perfil");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION){

            String fotoPath = chooser.getSelectedFile().getAbsolutePath();
            p.guardarFoto(fotoPath);
            ImageIcon foto= new ImageIcon(fotoPath);

            ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.jFotoPerfil.getWidth(), this.jFotoPerfil.getHeight(), Image.SCALE_DEFAULT));
            try {
                p.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            return fotoReal1;
        }
        return null;
    }
        private ImageIcon setFoto(String d){
            ImageIcon foto= new ImageIcon(d);

            ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.jFotoPerfil.getWidth(), this.jFotoPerfil.getHeight(), Image.SCALE_DEFAULT));

            return fotoReal1;
        }
        private void addComboBox(String ar[]){
            for(int i=0;i<ar.length;i++){
                this.cmb_amigos.addItem(ar[i]);
            }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_agregarPost;
    private javax.swing.JButton bot_buscarA;
    private javax.swing.JToggleButton bot_cerrarS;
    private javax.swing.JButton bot_fotoperfil;
    private javax.swing.JButton bot_verPerfil;
    private javax.swing.JComboBox cmb_amigos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jFotoPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbl_amigos;
    private javax.swing.JTextField txt_aPost;
    private javax.swing.JTextArea txt_amigos;
    private javax.swing.JTextArea txt_posts;
    // End of variables declaration//GEN-END:variables
}

