/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProfileAmigo.java
 *
 * Created on Dec 8, 2011, 3:05:17 PM
 */
package Clases;

import java.awt.Image;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Gustavo
 */
public class ProfileAmigo extends javax.swing.JFrame {

    /** Creates new form ProfileAmigo */
    public ProfileAmigo(String correo) {
        initComponents();
        Perfil p=new Perfil(correo);
        ManageFriends mf=new ManageFriends(correo);
        Posts po=new Posts(correo);
        this.jFotoPerfil.setSize(144,134);
        this.lbl_nom.setText(p.getNombre());
        this.jFotoPerfil.setIcon(setFoto(p.getFoto()));
        Calendar c=Calendar.getInstance();
        c.setTime(new Date(p.getFechaNacimiento()));
        this.txt_posts.setText(po.getPosts());
        this.jTextPane1.setText("Fecha de Nacimiento: \n"+p.fecha(c) +"\n\n"+
                                "Telefono: "+p.getTel()+"\n\n"+
                                "Correo: "+p.getEmail()+"\n\n"+
                                "Genero: "+p.getGenero());
        this.txt_amigos.setText(mf.listarAmigos());
        try {
            p.close();
            mf.cerrarConexion();
           po.cerrar();
        } catch (IOException ex) {
            System.out.println("ex");
        }
           
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nom = new javax.swing.JLabel();
        jFotoPerfil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_posts = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_amigos = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(943, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_nom.setFont(new java.awt.Font("Ravie", 2, 16));
        getContentPane().add(lbl_nom);
        lbl_nom.setBounds(10, 11, 335, 37);

        jFotoPerfil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 0)));
        getContentPane().add(jFotoPerfil);
        jFotoPerfil.setBounds(54, 66, 144, 134);

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(700, 50, 219, 230);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Informacion Personal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(714, 28, 180, 15);

        txt_posts.setEditable(false);
        jScrollPane2.setViewportView(txt_posts);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 292, 494, 176);

        txt_amigos.setEditable(false);
        jScrollPane3.setViewportView(txt_amigos);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(420, 50, 269, 230);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Amigos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(427, 28, 110, 15);

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(727, 410, 130, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Estados Recientes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 269, 170, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases/Imagenes/blanco-sobre-azul-wallpapers_27710_1920x1200.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 940, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ProfileAmigo("gustavo_ocampo@hotmail.com").setVisible(true);
            }
        });
    }
    
    private ImageIcon setFoto(String d){
            ImageIcon foto= new ImageIcon(d);

            ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.jFotoPerfil.getWidth(), this.jFotoPerfil.getHeight(), Image.SCALE_DEFAULT));

            return fotoReal1;
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jFotoPerfil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JTextPane txt_amigos;
    private javax.swing.JTextPane txt_posts;
    // End of variables declaration//GEN-END:variables
}
